import {adaptiveMultiskillFeedbackService} from '../services/adaptiveMultiskillFeedbackService';
import React,{useState}from'react';import{ArrowLeft,CheckCircle2,RotateCcw,CalendarClock}from'lucide-react';import{readingService}from'../services/readingService';
type P={language:'en'|'zh';slug:string;onNavigate:(p:string)=>void};
export function ReadingPracticePage({language,slug,onNavigate}:P){
 const p=readingService.getBySlug(slug,language);const[a,setA]=useState<Record<string,string>>({});const[score,setScore]=useState<number|null>(null);const[startedAt]=useState(()=>Date.now());
 if(!p)return <div className="p-20 text-white">Không tìm thấy bài đọc.</div>;
 const back='/'+(language==='en'?'tieng-anh':'tieng-trung')+'/reading';
 const submit=()=>{
 const nextAdaptivePlan=adaptiveMultiskillFeedbackService.recordResult({skill:'reading',language,activityId:p.id,score:s,completedAt:new Date().toISOString()});const correct=p.questions.filter(q=>a[q.id]===q.correctAnswer).length;const s=p.questions.length?Math.round(correct/p.questions.length*100):100;readingService.saveProgress({passageId:p.id,language,attempts:1,bestScore:s,lastScore:s,completed:s>=70,lastAttemptAt:new Date().toISOString()});setScore(s)};
 const reset=()=>{setA({});setScore(null)};
 return <div className="min-h-[75vh] bg-[#050505] py-10"><div className="mx-auto max-w-4xl px-5 sm:px-8">
  <button onClick={()=>onNavigate(back)} className="mb-8 flex items-center gap-2 text-xs text-[#888]"><ArrowLeft className="h-4 w-4"/>READING LAB</button>
  <div className="mb-8"><span className="text-xs font-mono text-[#D9FF3F]">{p.level} · {p.topic}</span><h1 className="mt-3 text-4xl font-black">{p.title}</h1><div className="mt-3 text-xs text-[#666]">{p.tags.join(' · ')}</div></div>
  <article className="border border-[#292929] bg-[#101010] p-6 text-base leading-8 text-[#ccc]">{p.content}</article>
  {p.translation&&<div className="mt-4 border border-[#222] bg-[#0c0c0c] p-5 text-sm leading-7 text-[#777]"><span className="mb-2 block text-[10px] font-mono text-[#D9FF3F]">VIỆT NGHĨA</span>{p.translation}</div>}
  <div className="mt-8 space-y-4"><div className="flex items-center justify-between"><div className="text-xs font-mono text-[#D9FF3F]">READING COMPREHENSION</div><span className="text-[10px] text-[#666]">{Object.keys(a).length}/{p.questions.length} câu đã chọn</span></div>
   {p.questions.map((q,i)=><div key={q.id} className="border border-[#222] bg-[#0d0d0d] p-5"><b className="text-sm">{i+1}. {q.question}</b><div className="mt-4 grid gap-2">{q.options.map(o=><button key={o} disabled={score!==null} onClick={()=>setA({...a,[q.id]:o})} className={(a[q.id]===o?'border-[#D9FF3F] bg-[#171c0d] text-white':'border-[#292929] text-[#aaa]')+' border p-3 text-left text-sm disabled:cursor-default'}>{o}</button>)}</div>{score!==null&&a[q.id]!==q.correctAnswer&&<div className="mt-3 text-xs leading-5 text-amber-300">Đáp án đúng: {q.correctAnswer}. {q.explanation}</div>}{score!==null&&a[q.id]===q.correctAnswer&&<div className="mt-3 text-xs text-[#D9FF3F]">✓ Chính xác. {q.explanation}</div>}</div>)}
   <div className="flex flex-wrap gap-3"><button onClick={submit} disabled={score!==null||Object.keys(a).length<p.questions.length} className="bg-[#D9FF3F] px-6 py-4 text-xs font-black text-black disabled:opacity-40">{score!==null?<><CheckCircle2 className="inline h-4 w-4 mr-2"/>ĐÃ LƯU KẾT QUẢ</>:'NỘP BÀI & CẬP NHẬT MASTERY'}</button>{score!==null&&<button onClick={reset} className="flex items-center gap-2 border border-[#292929] px-5 py-4 text-xs font-bold text-[#aaa]"><RotateCcw className="h-4 w-4"/>LÀM LẠI</button>}</div>
  </div>
  {score!==null&&<div className="mt-8 border border-[#D9FF3F]/30 bg-[#0d1107] p-6"><div className="text-[10px] font-mono text-[#D9FF3F]">READING MASTERY</div><div className="mt-1 text-4xl font-black">{score}/100</div><p className="mt-3 text-xs text-[#888]">Kết quả đã được nối vào Mastery và lịch Spaced Review. Thời gian luyện: {Math.max(1,Math.round((Date.now()-startedAt)/1000))} giây.</p><div className="mt-4 flex items-center gap-2 text-xs text-[#D9FF3F]"><CalendarClock className="h-4 w-4"/>Ôn lại sau {score>=80?'7 ngày':score>=60?'3 ngày':'1 ngày'}</div><button onClick={()=>onNavigate('/dashboard')} className="mt-5 bg-[#D9FF3F] px-5 py-3 text-xs font-black text-black">XEM TIẾN ĐỘ</button></div>}
 </div></div>
}